-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TYPE "public"."meeting_mode" AS ENUM('in_person', 'zoom');--> statement-breakpoint
CREATE TYPE "public"."meeting_preference" AS ENUM('in_person', 'zoom', 'either');--> statement-breakpoint
CREATE TYPE "public"."meeting_status" AS ENUM('pending', 'accepted', 'declined', 'canceled');--> statement-breakpoint
CREATE TYPE "public"."role" AS ENUM('student', 'tutor');--> statement-breakpoint
CREATE TABLE "users" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"email" varchar NOT NULL,
	"password" varchar NOT NULL,
	"first_name" varchar NOT NULL,
	"last_name" varchar NOT NULL,
	"role" "role" DEFAULT 'student' NOT NULL,
	"meeting_preference" "meeting_preference" DEFAULT 'either' NOT NULL,
	"email_verified_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_email_key" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE TABLE "tutor_profiles" (
	"user_id" bigint PRIMARY KEY NOT NULL,
	"bio" text
);
--> statement-breakpoint
CREATE TABLE "student_profiles" (
	"user_id" bigint PRIMARY KEY NOT NULL
);
--> statement-breakpoint
CREATE TABLE "subjects" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"code" varchar(32) NOT NULL,
	"name" varchar(120) NOT NULL,
	CONSTRAINT "subjects_code_key" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "availability_slots" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"tutor_id" bigint NOT NULL,
	"weekday" smallint,
	"date" date,
	"start_time" time NOT NULL,
	"end_time" time NOT NULL,
	"recurrence_rule" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "availability_slots_weekday_check" CHECK ((weekday >= 0) AND (weekday <= 6))
);
--> statement-breakpoint
CREATE TABLE "meeting_requests" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"student_id" bigint NOT NULL,
	"tutor_id" bigint NOT NULL,
	"subject_id" bigint NOT NULL,
	"requested_start" timestamp NOT NULL,
	"requested_end" timestamp NOT NULL,
	"mode" "meeting_mode" NOT NULL,
	"topic" text,
	"status" "meeting_status" DEFAULT 'pending' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "user_subjects" (
	"user_id" bigint NOT NULL,
	"subject_id" bigint NOT NULL,
	"role" "role" NOT NULL,
	CONSTRAINT "user_subjects_pkey" PRIMARY KEY("user_id","subject_id","role")
);
--> statement-breakpoint
ALTER TABLE "tutor_profiles" ADD CONSTRAINT "tutor_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "student_profiles" ADD CONSTRAINT "student_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "availability_slots" ADD CONSTRAINT "availability_slots_tutor_id_fkey" FOREIGN KEY ("tutor_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "meeting_requests" ADD CONSTRAINT "meeting_requests_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "meeting_requests" ADD CONSTRAINT "meeting_requests_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "public"."subjects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "meeting_requests" ADD CONSTRAINT "meeting_requests_tutor_id_fkey" FOREIGN KEY ("tutor_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_subjects" ADD CONSTRAINT "user_subjects_subject_id_fkey" FOREIGN KEY ("subject_id") REFERENCES "public"."subjects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_subjects" ADD CONSTRAINT "user_subjects_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
*/